### ISSUE TITLE
invgamma broken gradient

### ISSUE THREAD

**Issue by zenna** [zenna/Omega.jl#116]
We define invgamma randvar using quantile, but that uses cquantile which breaks gradient.

```
x = invgamma(1,1)
rand(x, softgt(x, 0); alg = HMCFAST)
```

I suppose this will apply to all functions that use cquantile

**Comment by jburroni** [comment]
the thing is that the gamma distribution doesn't have a closed for solution for the quantile function.
Generating samples from a gamma distribution given arbitrary arguments is a very hard to do deal.

**Comment by zenna** [comment]
A normal distribution doesn't have a closed form quantile either
