### ISSUE TITLE
Errors getting started with Omega (Installation and loading)

### ISSUE THREAD

**Issue by 3210jr** [zenna/Omega.jl#131]
Hey,

I've had a few challenges installing and getting started with Omega. The issues are:

**During installation in an existing environment:**
```
ERROR: Unsatisfiable requirements detected for package ZygoteRules [700de1a5]:
 ZygoteRules [700de1a5] log:
 ├─possible versions are: 0.2.0 or uninstalled
 ├─ZygoteRules [700de1a5] is fixed to version 0.2.0
 └─found to have no compatible versions left with Zygote [e88e6eb3] 
   └─Zygote [e88e6eb3] log:
     ├─possible versions are: [0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0-0.4.22, 0.5.0-0.5.4] or uninstalled
     └─restricted to versions 0.3.4-0.3 by Omega [1af16e33], leaving only versions 0.3.4
       └─Omega [1af16e33] log:
         ├─possible versions are: 0.1.1 or uninstalled
         └─Omega [1af16e33] is fixed to version 0.1.1
```

Installation works well in a brand new environment. But loading it results in this error:
```
ERROR: LoadError: LoadError: syntax: unexpected semicolon in tuple around /home/user/.julia/packages/Zygote/bdE6T/src/lib/lib.jl:30
```

I am running `julia 1.5` 

Any suggestions are greatly appreciated.
Thanks!

**Comment by zenna** [comment]
Looking into this.

**Comment by 3210jr** [comment]
Hey @zenna I saw the recent `Lang` branch updates! Tried it locally and with some other teammates who had the same issue and everything seems to work just fine so far.

Thanks for the AMAZING work! We literally love it so much and would be happy to be "[patreons](https://www.patreon.com/)" or support this work in any way our small team can.

**Comment by zenna** [comment]
Hi @3210jr, I'm doing a rewrite here https://github.com/zenna/OmegaCore.jl.  Will merge into the main repo when done.  What's your use case?  I never thought of Patreon.
