### ISSUE TITLE
Adjust Require file

### ISSUE THREAD

**Issue by rcalxrc08** [zenna/Omega.jl#26]
REQUIRE file:
```julia 
julia
Distributions
ProgressMeter
```

Mu.jl file:
```julia 
using Flux
using Distributions
using PDMats
using ProgressMeter
using Spec
```

**Comment by keorn** [comment]
Spec cant be added so `Pkg.clone("git@github.com:zenna/Spec.jl.git")` is needed post `clone`

**Comment by zenna** [comment]
Thanks. Yes I'll update this.  As you've noticed a few dependents aren't official packages.  I'm deciding whether to group them into a release, or just go to Pkg3 and julia0.7 which is a lot more flexible in what a package can depend on.

**Comment by zenna** [comment]
Moving to 0.7
